### ISSUE TITLE
No such method error in 1.9.20

### ISSUE THREAD

**Issue by sterfpaul** [lukehutch/fast-classpath-scanner#57]
I'm getting a NoSuchMethodError after updating to 1.9.20 on Java "1.8.0_91". 

`java.lang.NoSuchMethodError: io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.getUniqueClasspathElements()Ljava/util/ArrayList;`

Fast path is a dependency of JBrowserDriver where i'm getting this issue. See: https://github.com/MachinePublishers/jBrowserDriver/issues/137

**Comment by lukehutch** [comment]
Thanks, this is strange -- it is an exception caused by calling FastClasspathScanner's method using reflection, so it is probably an error with jBrowserDriver. I notice the linked bug says this is now fixed. Is there anything I need to look at still?

**Comment by sterfpaul** [comment]
The fix in JBrowserDriver is to use 1.9.19 . But it indeed seems like this is an issue in the JBrowserDriver implementation, so i don't think you need to look into it.

**Comment by sterfpaul** [comment]
It doesn't seem like they are using reflection so it's probably an interface change. That probably shouldn't happen in a minor release? Maybe you could check why the getUniqueClasspathElements is missing in the newer version.

**Comment by hollingsworthd** [comment]
It is odd. I can use 1.9.20 locally with no problems. My guess is this is caused by people's build process not doing a clean or something like that. I used version ranges in maven for jBrowserDriver... I disabled those. That could be a cause of the problem in itself if it is a problem in build tools.

**Comment by sterfpaul** [comment]
I've been using 'mvn clean test'  all morning when i had the problem. That should have done a clean. So yeah it's weird, i can't see any reason in the code (of either project) why this should cause a problem. 

I'll just close this if no more people have this problem.

**Comment by hollingsworthd** [comment]
@sterfpaul if you don't mind, in jBrowserDriver if you can try:

```xml
            <dependency>
                <groupId>io.github.lukehutch</groupId>
                <artifactId>fast-classpath-scanner</artifactId>
                <version>1.9.20</version>
            </dependency>
```

If that works then the problem would be caused by some Maven bugs in how it handles version ranges.

**Comment by sterfpaul** [comment]
Gives me the same exception when running mvn clean test:

> Caused by: java.lang.NoSuchMethodError: io.github.lukehutch.fastclasspathscanner.classpath.ClasspathFinder.getUniqueClasspathElements()Ljava/util/ArrayList;
> 	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<clinit>(JBrowserDriver.java:128)

**Comment by hollingsworthd** [comment]
Thanks, good to know. Is your project Java-based or some other language?

**Comment by sterfpaul** [comment]
Java

**Comment by hollingsworthd** [comment]
I was able to reproduce this. It's a maven bug related to caching of dependencies and the version range. 1.9.20 should work fine.

**Comment by sterfpaul** [comment]
So should work fine with version 0.14.6 of JBrowserDriver.

**Comment by hollingsworthd** [comment]
Yes, v0.14.6 of jBrowserDriver is fixed because it changed the Maven POM to avoid this Maven problem. There was never any real bug in Fast Classpath Scanner, it just happened to demonstrate this Maven issue.

**Comment by lukehutch** [comment]
OK, thanks for verifying.
